// Pre-built catalog of India's Got Latent episodes hosted on archive.org
// Generated automatically — zero Supabase dependency
const LOCAL_VIDEOS = [
  {
    "id": "ep-01",
    "dataId": "ep-01",
    "archive_id": "igl-ep-01",
    "title": "Episode 01 | ft. Raftaar",
    "description": "India's Got Latent Episode 1 featuring Raftaar.",
    "category": "season1",
    "episode_number": 1,
    "duration": "0h 43m 23s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/5v1v1r.webp",
    "video_url": "https://archive.org/download/igl-ep-01/Episode%2001%20ft.%20Raftaar%20%5Bep-01%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-01",
    "filename": "Episode 01 ft. Raftaar [ep-01].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-02",
    "dataId": "ep-02",
    "archive_id": "igl-ep-02",
    "title": "Episode 02 | ft. GamerFleet",
    "description": "India's Got Latent Episode 2 featuring GamerFleet.",
    "category": "season1",
    "episode_number": 2,
    "duration": "1h 6m 9s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/1wxwnb.webp",
    "video_url": "https://archive.org/download/igl-ep-02/Episode%2002%20ft.%20GamerFleet%20%5Bep-02%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-02",
    "filename": "Episode 02 ft. GamerFleet [ep-02].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-03",
    "dataId": "ep-03",
    "archive_id": "igl-ep-03",
    "title": "Episode 03 | ft. Urfi Javed, Ashish Solanki",
    "description": "India's Got Latent Episode 3 featuring Urfi Javed and Ashish Solanki.",
    "category": "season1",
    "episode_number": 3,
    "duration": "1h 5m 18s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/xavl0p.webp",
    "video_url": "https://archive.org/download/igl-ep-03/Episode%2003%20ft.%20Urfi%20Javed%20Ashish%20Solanki%20%5Bep-03%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-03",
    "filename": "Episode 03 ft. Urfi Javed Ashish Solanki [ep-03].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-04",
    "dataId": "ep-04",
    "archive_id": "igl-ep-04",
    "title": "Episode 04 | ft. Maheep Singh",
    "description": "India's Got Latent Episode 4 featuring Maheep Singh.",
    "category": "season1",
    "episode_number": 4,
    "duration": "1h 4m 57s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/h9krad.webp",
    "video_url": "https://archive.org/download/igl-ep-04/Episode%2004%20ft.%20Maheep%20Singh%20%5Bep-04%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-04",
    "filename": "Episode 04 ft. Maheep Singh [ep-04].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-05",
    "dataId": "ep-05",
    "archive_id": "igl-ep-05",
    "title": "Episode 05 | ft. Kunal Kamra, Atul Khatri",
    "description": "India's Got Latent Episode 5 featuring Kunal Kamra and Atul Khatri.",
    "category": "season1",
    "episode_number": 5,
    "duration": "1h 7m 26s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/wonjl6.webp",
    "video_url": "https://archive.org/download/igl-ep-05/Episode%2005%20ft.%20Kunal%20Kamra%20Atul%20Khatri%20%5Bep-05%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-05",
    "filename": "Episode 05 ft. Kunal Kamra Atul Khatri [ep-05].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-06",
    "dataId": "ep-06",
    "archive_id": "igl-ep-06",
    "title": "Episode 06 | ft. Vipul Goyal, Joke Singh",
    "description": "India's Got Latent Episode 6 featuring Vipul Goyal and Joke Singh.",
    "category": "season1",
    "episode_number": 6,
    "duration": "1h 5m 28s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/v99xxv.webp",
    "video_url": "https://archive.org/download/igl-ep-06/Episode%2006%20ft.%20Vipul%20Goyal%20Joke%20Singh%20%5Bep-06%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-06",
    "filename": "Episode 06 ft. Vipul Goyal Joke Singh [ep-06].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-07",
    "dataId": "ep-07",
    "archive_id": "igl-ep-07",
    "title": "Episode 07 | ft. Ravi Gupta, Rahgir",
    "description": "India's Got Latent Episode 7 featuring Ravi Gupta and Rahgir.",
    "category": "season1",
    "episode_number": 7,
    "duration": "1h 1m 19s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/dycm14.webp",
    "video_url": "https://archive.org/download/igl-ep-07/Episode%2007%20ft.%20Ravi%20Gupta%20Rahgir%20%5Bep-07%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-07",
    "filename": "Episode 07 ft. Ravi Gupta Rahgir [ep-07].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-08",
    "dataId": "ep-08",
    "archive_id": "igl-ep-08",
    "title": "Episode 08 | ft. Poonam Pandey, Vidit C",
    "description": "India's Got Latent Episode 8 featuring Poonam Pandey and Vidit C.",
    "category": "season1",
    "episode_number": 8,
    "duration": "0h 54m 31s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/b9cjfx.webp",
    "video_url": "https://archive.org/download/igl-ep-08/Episode%2008%20ft.%20Poonam%20Pandey%20Vidit%20C%20%5Bep-08%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-08",
    "filename": "Episode 08 ft. Poonam Pandey Vidit C [ep-08].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-09",
    "dataId": "ep-09",
    "archive_id": "igl-ep-09",
    "title": "Episode 09 | ft. Deepak Kalal, Manan Desai",
    "description": "India's Got Latent Episode 9 featuring Deepak Kalal and Manan Desai.",
    "category": "season1",
    "episode_number": 9,
    "duration": "1h 3m 59s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/g4teuh.webp",
    "video_url": "https://archive.org/download/igl-ep-09/Episode%2009%20ft.%20Deepak%20Kalal%20Manan%20Desai%20%5Bep-09%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-09",
    "filename": "Episode 09 ft. Deepak Kalal Manan Desai [ep-09].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-10",
    "dataId": "ep-10",
    "archive_id": "igl-ep-10",
    "title": "Episode 10 | ft. Raghu Ram, Tanmay Bhat",
    "description": "India's Got Latent Episode 10 featuring Raghu Ram and Tanmay Bhat.",
    "category": "season1",
    "episode_number": 10,
    "duration": "1h 8m 24s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/37nxmd.webp",
    "video_url": "https://archive.org/download/igl-ep-10/Episode%2010%20ft.%20Raghu%20Ram%20Tanmay%20Bhat%20%5Bep-10%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-10",
    "filename": "Episode 10 ft. Raghu Ram Tanmay Bhat [ep-10].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-11",
    "dataId": "ep-11",
    "archive_id": "igl-ep-11",
    "title": "Episode 11 | ft. Bharti Singh, Haarsh Limbachiyaa",
    "description": "India's Got Latent Episode 11 featuring Bharti Singh and Haarsh Limbachiyaa.",
    "category": "season1",
    "episode_number": 11,
    "duration": "1h 15m 10s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/8j55ug.webp",
    "video_url": "https://archive.org/download/igl-ep-11/Episode%2011%20ft.%20Bharti%20Singh%20Haarsh%20Limbachiyaa%20%5Bep-11%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-11",
    "filename": "Episode 11 ft. Bharti Singh Haarsh Limbachiyaa [ep-11].mp4",
    "youtubeId": null
  },
  {
    "id": "ep-12",
    "dataId": "ep-12",
    "archive_id": "igl-ep-12",
    "title": "Episode 12 | ft. Rakhi Sawant, Ashish Solanki",
    "description": "India's Got Latent Episode 12 featuring Rakhi Sawant and Ashish Solanki.",
    "category": "season1",
    "episode_number": 12,
    "duration": "1h 14m 52s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/p88fof.webp",
    "video_url": "https://archive.org/download/igl-ep-12/Episode%2012%20ft.%20Rakhi%20Sawant%20Ashish%20Solanki%20%5Bep-12%5D.mp4",
    "archive_url": "https://archive.org/details/igl-ep-12",
    "filename": "Episode 12 ft. Rakhi Sawant Ashish Solanki [ep-12].mp4",
    "youtubeId": null
  },
  {
    "id": "bonus-01",
    "dataId": "bonus-01",
    "archive_id": "igl-bonus-01",
    "title": "Bonus Segment 01 | ft. Arpit Bala",
    "description": "Bonus segment 1 featuring Arpit Bala.",
    "category": "s1bonus",
    "episode_number": 1,
    "duration": "0h 36m 6s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/zqtar6.webp",
    "video_url": "https://archive.org/download/igl-bonus-01/Bonus%20Segment%2001%20ft.%20Arpit%20Bala%20%5Bbonus-01%5D.mp4",
    "archive_url": "https://archive.org/details/igl-bonus-01",
    "filename": "Bonus Segment 01 ft. Arpit Bala [bonus-01].mp4",
    "youtubeId": null
  },
  {
    "id": "extra-01",
    "dataId": "extra-01",
    "archive_id": "igl-extra-01",
    "title": "Bonus Segment 07 | ft. Deepak Kalal",
    "description": "Extra segment featuring Deepak Kalal.",
    "category": "s1bonus",
    "episode_number": 1,
    "duration": "0h 36m 31s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/mi1fo1.webp",
    "video_url": "https://archive.org/download/igl-extra-01/Bonus%20Segment%2007%20ft.%20Deepak%20Kalal%20%5Bextra-01%5D.mp4",
    "archive_url": "https://archive.org/details/igl-extra-01",
    "filename": "Bonus Segment 07 ft. Deepak Kalal [extra-01].mp4",
    "youtubeId": null
  },
  {
    "id": "bonus-02",
    "dataId": "bonus-02",
    "archive_id": "igl-bonus-02",
    "title": "Bonus Segment 02 | ft. Badshah, Siddhant Chaturvedi",
    "description": "Bonus segment 2 featuring Badshah and Siddhant Chaturvedi.",
    "category": "s1bonus",
    "episode_number": 2,
    "duration": "0h 52m 8s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/zozibh.webp",
    "video_url": "https://archive.org/download/igl-bonus-02/Bonus%20Segment%2002%20ft.%20Badshah%20Siddhant%20Chaturvedi%20%5Bbonus-02%5D.mp4",
    "archive_url": "https://archive.org/details/igl-bonus-02",
    "filename": "Bonus Segment 02 ft. Badshah Siddhant Chaturvedi [bonus-02].mp4",
    "youtubeId": null
  },
  {
    "id": "extra-02",
    "dataId": "extra-02",
    "archive_id": "igl-extra-02",
    "title": "Bonus Segment 08 | ft. Raghu Ram",
    "description": "Extra segment featuring Raghu Ram.",
    "category": "s1bonus",
    "episode_number": 2,
    "duration": "0h 34m 7s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/ckvmsi.webp",
    "video_url": "https://archive.org/download/igl-extra-02/Bonus%20Segment%2008%20ft.%20Raghu%20Ram%20%5Bextra-02%5D.mp4",
    "archive_url": "https://archive.org/details/igl-extra-02",
    "filename": "Bonus Segment 08 ft. Raghu Ram [extra-02].mp4",
    "youtubeId": null
  },
  {
    "id": "bonus-03",
    "dataId": "bonus-03",
    "archive_id": "igl-bonus-03",
    "title": "Bonus Segment 03 | ft. Avika Gor",
    "description": "Bonus segment 3 featuring Avika Gor.",
    "category": "s1bonus",
    "episode_number": 3,
    "duration": "0h 54m 22s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/eyst23.webp",
    "video_url": "https://archive.org/download/igl-bonus-03/Bonus%20Segment%2003%20ft.%20Avika%20Gor%20%5Bbonus-03%5D.mp4",
    "archive_url": "https://archive.org/details/igl-bonus-03",
    "filename": "Bonus Segment 03 ft. Avika Gor [bonus-03].mp4",
    "youtubeId": null
  },
  {
    "id": "extra-03",
    "dataId": "extra-03",
    "archive_id": "igl-extra-03",
    "title": "Discarded Segment 01 | ft. Aakash Gupta, Anubhav Bassi",
    "description": "Discarded segment featuring Aakash Gupta and Anubhav Bassi.",
    "category": "s1bonus",
    "episode_number": 3,
    "duration": "0h 27m 41s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/p74kpp.webp",
    "video_url": "https://archive.org/download/igl-extra-03/Discarded%20Segment%2001%20ft.%20Aakash%20Gupta%20Anubhav%20Bassi%20%5Bextra-03%5D.mp4",
    "archive_url": "https://archive.org/details/igl-extra-03",
    "filename": "Discarded Segment 01 ft. Aakash Gupta Anubhav Bassi [extra-03].mp4",
    "youtubeId": null
  },
  {
    "id": "bonus-04",
    "dataId": "bonus-04",
    "archive_id": "igl-bonus-04",
    "title": "Bonus Segment 04 | ft. Seedhe Maut, Madhur Virli",
    "description": "Bonus segment 4 featuring Seedhe Maut and Madhur Virli.",
    "category": "s1bonus",
    "episode_number": 4,
    "duration": "1h 12m 24s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/sykxlk.webp",
    "video_url": "https://archive.org/download/igl-bonus-04/Bonus%20Segment%2004%20ft.%20Seedhe%20Maut%20Madhur%20Virli%20%5Bbonus-04%5D.mp4",
    "archive_url": "https://archive.org/details/igl-bonus-04",
    "filename": "Bonus Segment 04 ft. Seedhe Maut Madhur Virli [bonus-04].mp4",
    "youtubeId": null
  },
  {
    "id": "extra-04",
    "dataId": "extra-04",
    "archive_id": "igl-extra-04",
    "title": "Deleted Footage",
    "description": "Deleted footage compilation.",
    "category": "s1bonus",
    "episode_number": 4,
    "duration": "0h 39m 31s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/s654fa.webp",
    "video_url": "https://archive.org/download/igl-extra-04/Deleted%20Footage%20%5Bextra-04%5D.mp4",
    "archive_url": "https://archive.org/details/igl-extra-04",
    "filename": "Deleted Footage [extra-04].mp4",
    "youtubeId": null
  },
  {
    "id": "bonus-05",
    "dataId": "bonus-05",
    "archive_id": "igl-bonus-05",
    "title": "Bonus Segment 05 | ft. Rohan Joshi",
    "description": "Bonus segment 5 featuring Rohan Joshi.",
    "category": "s1bonus",
    "episode_number": 5,
    "duration": "1h 29m 5s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/x6ieup.webp",
    "video_url": "https://archive.org/download/igl-bonus-05/Bonus%20Segment%2005%20ft.%20Rohan%20Joshi%20%5Bbonus-05%5D.mp4",
    "archive_url": "https://archive.org/details/igl-bonus-05",
    "filename": "Bonus Segment 05 ft. Rohan Joshi [bonus-05].mp4",
    "youtubeId": null
  },
  {
    "id": "bonus-06",
    "dataId": "bonus-06",
    "archive_id": "igl-bonus-06",
    "title": "Bonus Segment 06 | ft. Ranveer Allahbadia",
    "description": "Bonus segment 6 featuring Ranveer Allahbadia.",
    "category": "s1bonus",
    "episode_number": 6,
    "duration": "1h 3m 9s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/vlhczg.webp",
    "video_url": "https://archive.org/download/igl-bonus-06/Bonus%20Segment%2006%20ft.%20Ranveer%20Allahbadia%20%5Bbonus-06%5D.mp4",
    "archive_url": "https://archive.org/details/igl-bonus-06",
    "filename": "Bonus Segment 06 ft. Ranveer Allahbadia [bonus-06].mp4",
    "youtubeId": null
  },
  {
    "id": "s2-01",
    "dataId": "s2-01",
    "archive_id": "igl-s2-01",
    "title": "Season 2 Episode 01 | ft. Alia Bhatt, Sharvari, Ashish Solanki",
    "description": "Full episode online stream. Free community fan archive.",
    "category": "season2",
    "episode_number": 1,
    "duration": "",
    "thumbnail_url": "https://i.ytimg.com/vi/eHTXQW58WhA/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-s2-01/Season%202%20Episode%2001%20ft.%20Alia%20Bhatt%20Sharvari%20Ashish%20Solanki%20%5Bs2-01%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-01",
    "filename": "Season 2 Episode 01 ft. Alia Bhatt Sharvari Ashish Solanki [s2-01].mp4",
    "youtubeId": "eHTXQW58WhA"
  },
  {
    "id": "s2-02",
    "dataId": "s2-02",
    "archive_id": "igl-s2-02",
    "title": "Season 2 Episode 02 | ft. Harssh Limbachiya, Kiku Sharda, Chandan Prabhakar",
    "description": "India's Got Latent Season 2 Episode 2 featuring Harssh Limbachiya, Kiku Sharda and Chandan Prabhakar.",
    "category": "season2",
    "episode_number": 1,
    "duration": "",
    "thumbnail_url": "https://i.ytimg.com/vi/c35fpGWqXnk/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-s2-02/Season%202%20Episode%2002%20ft.%20Harssh%20Limbachiya%20Kiku%20Sharda%20Chandan%20Prabhakar%20%5Bs2-02%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-02",
    "filename": "Season 2 Episode 02 ft. Harssh Limbachiya Kiku Sharda Chandan Prabhakar [s2-02].mp4",
    "youtubeId": "c35fpGWqXnk"
  },
  {
    "id": "s2-03",
    "dataId": "s2-03",
    "archive_id": "igl-s2-03",
    "title": "Season 2 Episode 03 | ft. Raghu Ram, Vishal Dadlani, Tanmay Bhat, Yashraj",
    "description": "India's Got Latent Season 2 Episode 3 featuring Raghu Ram, Vishal Dadlani, Tanmay Bhat, and Yashraj.",
    "category": "season2",
    "episode_number": 1,
    "duration": "53m 43s",
    "thumbnail_url": "https://i.ytimg.com/vi/aSR1tndcaLE/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-s2-03/Season%202%20Episode%2003%20ft.%20Raghu%20Ram%20Vishal%20Dadlani%20Tanmay%20Bhat%20Yashraj%20%5Bs2-03%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-03",
    "filename": "Season 2 Episode 03 ft. Raghu Ram Vishal Dadlani Tanmay Bhat Yashraj [s2-03].mp4",
    "youtubeId": "aSR1tndcaLE"
  },
  {
    "id": "s2-04",
    "dataId": "s2-04",
    "archive_id": "igl-s2-04",
    "title": "INDIA'S GOT LATENT S2 EP4 ft. Karan Aujla, Tanmay Bhat, Gurleen Pannu, Rahul Dua",
    "description": "India's Got Latent Season 2 Episode 4 featuring Karan Aujla, Tanmay Bhat, Gurleen Pannu, and Rahul Dua.",
    "category": "season2",
    "episode_number": 4,
    "duration": "53m 53s",
    "thumbnail_url": "https://i.ytimg.com/vi/B6NVvtIz9_Q/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-s2-04/INDIAS%20GOT%20LATENT%20S2%20EP4%20ft.%20Karan%20Aujla%20Tanmay%20Bhat%20Gurleen%20Pannu%20Rahul%20Dua%20%5Bs2-04%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-04",
    "filename": "INDIAS GOT LATENT S2 EP4 ft. Karan Aujla Tanmay Bhat Gurleen Pannu Rahul Dua [s2-04].mp4",
    "youtubeId": "B6NVvtIz9_Q"
  },
  {
    "id": "s2-05",
    "dataId": "s2-05",
    "archive_id": "igl-s2-05",
    "title": "INDIA'S GOT LATENT S2 EP5 ft. Orry, Archana Puran Singh, Sharon Verma, Nishant Suri",
    "description": "Season 2 Episode 05 ft. Orry, Archana Puran Singh, Sharon Verma, Nishant Suri.",
    "category": "season2",
    "episode_number": 5,
    "duration": "0h 50m 0s",
    "thumbnail_url": "https://i.ytimg.com/vi/VJ9VC9OqdAA/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-s2-05/INDIAS%20GOT%20LATENT%20S2%20EP5%20ft.%20Orry%20Archana%20Puran%20Singh%20Sharon%20Verma%20Nishant%20Suri%20%5Bs2-05%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-05",
    "filename": "INDIAS GOT LATENT S2 EP5 ft. Orry Archana Puran Singh Sharon Verma Nishant Suri [s2-05].mp4",
    "youtubeId": "VJ9VC9OqdAA"
  },
  {
    "id": "s2-06-rakhi",
    "dataId": "s2-06-rakhi",
    "archive_id": "igl-s2-06-rakhi",
    "title": "INDIA'S GOT LATENT S2 EP6 ft. Rakhi Sawant, Ashneer Grover, Kushagra Srivastava",
    "description": "Season 2 Episode 06 ft. Rakhi Sawant, Ashneer Grover, Kushagra Srivastava.",
    "category": "season2",
    "episode_number": 6,
    "duration": "0h 52m 26s",
    "thumbnail_url": "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2026/09/file-image-2026-09-06t132444-1788681256.webp",
    "video_url": "https://archive.org/download/igl-s2-06-rakhi/INDIAS%20GOT%20LATENT%20S2%20EP6%20ft.%20Rakhi%20Sawant%20Ashneer%20Grover%20Kushagra%20Srivastava%20%5Bs2-06-rakhi%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-06-rakhi",
    "filename": "INDIAS GOT LATENT S2 EP6 ft. Rakhi Sawant Ashneer Grover Kushagra Srivastava [s2-06-rakhi].mp4",
    "youtubeId": null
  },
  {
    "id": "s2-06",
    "dataId": "s2-06",
    "archive_id": "igl-s2-06",
    "title": "INDIA'S GOT LATENT S2 EP6 ft. Varun Dhawan, Medha Shankar, Nishant Tanwar, Sharon Verma",
    "description": "Season 2 Episode 06 ft. Varun Dhawan, Medha Shankar, Nishant Tanwar, Sharon Verma.",
    "category": "season2",
    "episode_number": 6,
    "duration": "0h 43m 0s",
    "thumbnail_url": "https://i.ytimg.com/vi/WE1zey_q8Ak/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-s2-06/INDIAS%20GOT%20LATENT%20S2%20EP6%20ft.%20Varun%20Dhawan%20Medha%20Shankar%20Nishant%20Tanwar%20Sharon%20Ve%20%5Bs2-06%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-06",
    "filename": "INDIAS GOT LATENT S2 EP6 ft. Varun Dhawan Medha Shankar Nishant Tanwar Sharon Ve [s2-06].mp4",
    "youtubeId": "WE1zey_q8Ak"
  },
  {
    "id": "s2-07",
    "dataId": "s2-07",
    "archive_id": "igl-s2-07",
    "title": "INDIA'S GOT LATENT S2 EP7 ft. Nawazuddin Siddiqui, Bhuvan Bam, Mukesh Chhabra, Kaustubh Agarwal",
    "description": "Season 2 Episode 07 ft. Nawazuddin Siddiqui, Bhuvan Bam, Mukesh Chhabra, Kaustubh Agarwal.",
    "category": "season2",
    "episode_number": 7,
    "duration": "0h 50m 0s",
    "thumbnail_url": "https://i.ytimg.com/vi/rkKZIMPecRA/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-s2-07/INDIAS%20GOT%20LATENT%20S2%20EP7%20ft.%20Nawazuddin%20Siddiqui%20Bhuvan%20Bam%20Mukesh%20Chhabra%20Kaust%20%5Bs2-07%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-07",
    "filename": "INDIAS GOT LATENT S2 EP7 ft. Nawazuddin Siddiqui Bhuvan Bam Mukesh Chhabra Kaust [s2-07].mp4",
    "youtubeId": "rkKZIMPecRA"
  },
  {
    "id": "s2-bonus-clip-01",
    "dataId": "s2-bonus-clip-01",
    "archive_id": "igl-s2-bonus-clip-01",
    "title": "Latent BONUS CLIP ft. Karan Aujla, Tanmay Bhat, Gurleen Pannu, Rahul Dua",
    "description": "Bonus clip from India's Got Latent Season 2 featuring Karan Aujla, Tanmay Bhat, Gurleen Pannu, and Rahul Dua.",
    "category": "s2bonus",
    "episode_number": 1,
    "duration": "0h 8m 23s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/rI-Cj3Kitx4.webp",
    "video_url": "https://archive.org/download/igl-s2-bonus-clip-01/Latent%20BONUS%20CLIP%20ft.%20Karan%20Aujla%20Tanmay%20Bhat%20Gurleen%20Pannu%20Rahul%20Dua%20%5Bs2-bonus-clip-01%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-bonus-clip-01",
    "filename": "Latent BONUS CLIP ft. Karan Aujla Tanmay Bhat Gurleen Pannu Rahul Dua [s2-bonus-clip-01].mp4",
    "youtubeId": null
  },
  {
    "id": "s2-bonus-ep1",
    "dataId": "s2-bonus-ep1",
    "archive_id": "igl-s2-bonus-ep1",
    "title": "S2 Bonus EP1 | ft. Raghav Juyal, Munawar, Niharika NM, Rohan Joshi",
    "description": "Season 2 Bonus episode featuring Raghav Juyal, Munawar, Niharika NM, and Rohan Joshi.",
    "category": "s2bonus",
    "episode_number": 1,
    "duration": "0h 57m 14s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/q8amKPDt_iY.webp",
    "video_url": "https://archive.org/download/igl-s2-bonus-ep1/S2%20Bonus%20EP1%20ft.%20Raghav%20Juyal%20Munawar%20Niharika%20NM%20Rohan%20Joshi%20%5Bs2-bonus-ep1%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-bonus-ep1",
    "filename": "S2 Bonus EP1 ft. Raghav Juyal Munawar Niharika NM Rohan Joshi [s2-bonus-ep1].mp4",
    "youtubeId": null
  },
  {
    "id": "s2-bonus-ep2",
    "dataId": "s2-bonus-ep2",
    "archive_id": "igl-s2-bonus-ep2",
    "title": "S2 Bonus EP2 | ft. Badshah, Sourav Joshi, Harssh Limbachiyaa, Rajat Sood",
    "description": "Season 2 Bonus episode featuring Badshah, Sourav Joshi, Harssh Limbachiyaa, and Rajat Sood.",
    "category": "s2bonus",
    "episode_number": 2,
    "duration": "0h 40m 0s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/otawyZaOxvs.webp",
    "video_url": "https://archive.org/download/igl-s2-bonus-ep2/S2%20Bonus%20EP2%20ft.%20Badshah%20Sourav%20Joshi%20Harssh%20Limbachiyaa%20Rajat%20Sood%20%5Bs2-bonus-ep2%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-bonus-ep2",
    "filename": "S2 Bonus EP2 ft. Badshah Sourav Joshi Harssh Limbachiyaa Rajat Sood [s2-bonus-ep2].mp4",
    "youtubeId": null
  },
  {
    "id": "s2-03-bonus",
    "dataId": "s2-03-bonus",
    "archive_id": "igl-s2-03-bonus",
    "title": "INDIA'S GOT LATENT S2 Bonus EP 3 ft. Deepak Kalal, Ravi Gupta, Agu Stanley",
    "description": "Season 2 Bonus Episode 03 ft. Deepak Kalal, Ravi Gupta, Agu Stanley.",
    "category": "s2bonus",
    "episode_number": 3,
    "duration": "0h 34m 27s",
    "thumbnail_url": "https://i.ytimg.com/vi/fzyL44FH2fI/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-s2-03-bonus/INDIAS%20GOT%20LATENT%20S2%20Bonus%20EP%203%20ft.%20Deepak%20Kalal%20Ravi%20Gupta%20Agu%20Stanley%20%5Bs2-03-bonus%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-03-bonus",
    "filename": "INDIAS GOT LATENT S2 Bonus EP 3 ft. Deepak Kalal Ravi Gupta Agu Stanley [s2-03-bonus].mp4",
    "youtubeId": "fzyL44FH2fI"
  },
  {
    "id": "s2-08",
    "dataId": "s2-08",
    "archive_id": "igl-s2-08",
    "title": "INDIA\u2019S GOT LATENT S2 Bonus EP 4 ft. Ayushmann Khurrana, Suhani Shah, Kullu, Rajat Sood",
    "description": "INDIA\u2019S GOT LATENT S2 Bonus EP 4 ft. Ayushmann Khurrana, Suhani Shah, Kullu, Rajat Sood\nThank you for supporting the channel members!! \u2764\ufe0f\n",
    "category": "s2bonus",
    "episode_number": 4,
    "duration": "34m",
    "thumbnail_url": "https://i.ytimg.com/vi/NQ6gWHMvna8/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-s2-08/INDIAS%20GOT%20LATENT%20S2%20Bonus%20EP%204%20ft.%20Ayushmann%20Khurrana%20Suhani%20Shah%20Kullu%20Rajat%20S%20%5Bs2-08%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-08",
    "filename": "INDIAS GOT LATENT S2 Bonus EP 4 ft. Ayushmann Khurrana Suhani Shah Kullu Rajat S [s2-08].mp4",
    "youtubeId": "NQ6gWHMvna8"
  },
  {
    "id": "s2-bts-01",
    "dataId": "s2-bts-01",
    "archive_id": "igl-s2-bts-01",
    "title": "BTS 01 | ft. Alia Bhatt, Sharvari, Ashish Solanki",
    "description": "Behind the scenes featuring Alia Bhatt, Sharvari, and Ashish Solanki.",
    "category": "s2bts",
    "episode_number": 1,
    "duration": "0h 17m 35s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/4z062p.webp",
    "video_url": "https://archive.org/download/igl-s2-bts-01/BTS%2001%20ft.%20Alia%20Bhatt%20Sharvari%20Ashish%20Solanki%20%5Bs2-bts-01%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-bts-01",
    "filename": "BTS 01 ft. Alia Bhatt Sharvari Ashish Solanki [s2-bts-01].mp4",
    "youtubeId": null
  },
  {
    "id": "s2-bts-02",
    "dataId": "s2-bts-02",
    "archive_id": "igl-s2-bts-02",
    "title": "BTS 02 | ft. Chandan Prabhakar, Harssh Limbachyaa, Kiku Sharda",
    "description": "Behind the scenes featuring Chandan Prabhakar, Harssh Limbachyaa, and Kiku Sharda.",
    "category": "s2bts",
    "episode_number": 2,
    "duration": "0h 15m 13s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/pfHrIXiqI4w.webp",
    "video_url": "https://archive.org/download/igl-s2-bts-02/BTS%2002%20ft.%20Chandan%20Prabhakar%20Harssh%20Limbachyaa%20Kiku%20Sharda%20%5Bs2-bts-02%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-bts-02",
    "filename": "BTS 02 ft. Chandan Prabhakar Harssh Limbachyaa Kiku Sharda [s2-bts-02].mp4",
    "youtubeId": null
  },
  {
    "id": "s2-bts-03",
    "dataId": "s2-bts-03",
    "archive_id": "igl-s2-bts-03",
    "title": "BTS 03 | ft. Raghu Ram, Tanmay Bhat, Vishal Dadlani",
    "description": "Behind the scenes featuring Raghu Ram, Tanmay Bhat, and Vishal Dadlani.",
    "category": "s2bts",
    "episode_number": 3,
    "duration": "0h 10m 0s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/eOIrKDKVZqE.webp",
    "video_url": "https://archive.org/download/igl-s2-bts-03/BTS%2003%20ft.%20Raghu%20Ram%20Tanmay%20Bhat%20Vishal%20Dadlani%20%5Bs2-bts-03%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-bts-03",
    "filename": "BTS 03 ft. Raghu Ram Tanmay Bhat Vishal Dadlani [s2-bts-03].mp4",
    "youtubeId": null
  },
  {
    "id": "s2-bts-04",
    "dataId": "s2-bts-04",
    "archive_id": "igl-s2-bts-04",
    "title": "Latent BTS ft. Karan Aujla, Tanmay Bhat, Gurleen Pannu, Rahul Dua",
    "description": "Behind the scenes from India's Got Latent Season 2 featuring Karan Aujla, Tanmay Bhat, Gurleen Pannu, and Rahul Dua.",
    "category": "s2bts",
    "episode_number": 4,
    "duration": "0h 14m 48s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/JpYbltLq2cs.webp",
    "video_url": "https://archive.org/download/igl-s2-bts-04/Latent%20BTS%20ft.%20Karan%20Aujla%20Tanmay%20Bhat%20Gurleen%20Pannu%20Rahul%20Dua%20%5Bs2-bts-04%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-bts-04",
    "filename": "Latent BTS ft. Karan Aujla Tanmay Bhat Gurleen Pannu Rahul Dua [s2-bts-04].mp4",
    "youtubeId": null
  },
  {
    "id": "special-01",
    "dataId": "special-01",
    "archive_id": "igl-special-01",
    "title": "Comedy Special 01 | Samay Raina - Still Alive",
    "description": "Standup comedy special stream. Non-commercial collection.",
    "category": "special",
    "episode_number": 1,
    "duration": "",
    "thumbnail_url": "https://i.ytimg.com/vi/LhpZJwUboeI/hqdefault.jpg",
    "video_url": "https://archive.org/download/igl-special-01/Comedy%20Special%2001%20Samay%20Raina%20-%20Still%20Alive%20%5Bspecial-01%5D.mp4",
    "archive_url": "https://archive.org/details/igl-special-01",
    "filename": "Comedy Special 01 Samay Raina - Still Alive [special-01].mp4",
    "youtubeId": "LhpZJwUboeI"
  },
  {
    "id": "s2-stillalive",
    "dataId": "s2-stillalive",
    "archive_id": "igl-s2-stillalive",
    "title": "STILL ALIVE - Mumbai Documentary",
    "description": "Mumbai documentary by Samay Raina.",
    "category": "special",
    "episode_number": 1,
    "duration": "0h 35m 0s",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/_IxqDcOiZJU.webp",
    "video_url": "https://archive.org/download/igl-s2-stillalive/STILL%20ALIVE%20-%20Mumbai%20Documentary%20%5Bs2-stillalive%5D.mp4",
    "archive_url": "https://archive.org/details/igl-s2-stillalive",
    "filename": "STILL ALIVE - Mumbai Documentary [s2-stillalive].mp4",
    "youtubeId": null
  },
  {
    "id": "kapil-01",
    "dataId": "kapil-01",
    "archive_id": "igl-kapil-01",
    "title": "Talk Show Segment 01 | ft. Samay Raina, BeerBiceps",
    "description": "The Great Indian Kapil Show \u2014 Season 4 Episode 14.",
    "category": "special",
    "episode_number": 1,
    "duration": "",
    "thumbnail_url": "https://indiassgottlatent.freeforall.dev/img/dna7vi.webp",
    "video_url": "https://archive.org/download/igl-kapil-01/Talk%20Show%20Segment%2001%20ft.%20Samay%20Raina%20BeerBiceps%20%5Bkapil-01%5D.mp4",
    "archive_url": "https://archive.org/details/igl-kapil-01",
    "filename": "Talk Show Segment 01 ft. Samay Raina BeerBiceps [kapil-01].mp4",
    "youtubeId": null
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = LOCAL_VIDEOS;
}
